version: '3'

volumes:
  db_vol2:
    driver: "local"
  queue_vol:
    driver: "local"

services:
  db:
    image: library/postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db_vol2:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  queue:
    image: gabrirabbit-manage
    #volumes: 
    #  - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
    environment: 
       - RABBITMQ_NODENAME=rabbit@queue
    volumes: 
       - queue_vol:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "8080:15672"
