version: '3'

volumes:
  db_vol:
    driver: "local"

services:
  db:
    image: library/postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
  queue:
    image: gabrirabbit-manage
    volumes: 
      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
    ports:
      - "5672:5672"
      - "8080:15672"
